POST http://localhost:9200/melonade-docker-compose-event/event/_mapping HTTP/1.1
Content-Type: application/json

{
  "event": {
    "properties": {
      "details": {
        "properties": {
          "ackTimeout": {
            "type": "date"
          },
          "createTime": {
            "type": "date"
          },
          "endTime": {
            "type": "date"
          },
          "input": {
            "type": "object",
            "enabled": false
          },
          "isRetried": {
            "type": "boolean"
          },
          "logs": {
            "type": "text"
          },
          "output": {
            "type": "object",
            "enabled": false
          },
          "parallelTasks": {
            "type": "object",
            "enabled": false
          },
          "retries": {
            "type": "long"
          },
          "retryDelay": {
            "type": "long"
          },
          "startTime": {
            "type": "date"
          },
          "status": {
            "type": "keyword"
          },
          "tags": {
            "type": "keyword"
          },
          "taskId": {
            "type": "keyword"
          },
          "taskName": {
            "type": "keyword"
          },
          "taskReferenceName": {
            "type": "keyword"
          },
          "timeout": {
            "type": "long"
          },
          "transactionId": {
            "type": "keyword"
          },
          "type": {
            "type": "keyword"
          },
          "workflowDefinition": {
            "properties": {
              "description": {
                "type": "text"
              },
              "failureStrategy": {
                "type": "keyword"
              },
              "name": {
                "type": "keyword"
              },
              "outputParameters": {
                "type": "object",
                "enabled": false
              },
              "rev": {
                "type": "keyword"
              },
              "tasks": {
                "properties": {
                  "ackTimeout": {
                    "type": "long"
                  },
                  "inputParameters": {
                    "type": "object",
                    "enabled": false
                  },
                  "name": {
                    "type": "keyword"
                  },
                  "parallelTasks": {
                    "properties": {
                      "ackTimeout": {
                        "type": "long"
                      },
                      "inputParameters": {
                        "type": "object",
                        "enabled": false
                      },
                      "name": {
                        "type": "keyword"
                      },
                      "retry": {
                        "properties": {
                          "delay": {
                            "type": "long"
                          },
                          "limit": {
                            "type": "long"
                          }
                        }
                      },
                      "taskReferenceName": {
                        "type": "keyword"
                      },
                      "timeout": {
                        "type": "long"
                      },
                      "type": {
                        "type": "keyword"
                      }
                    }
                  },
                  "retry": {
                    "properties": {
                      "delay": {
                        "type": "long"
                      },
                      "limit": {
                        "type": "long"
                      }
                    }
                  },
                  "taskReferenceName": {
                    "type": "keyword"
                  },
                  "timeout": {
                    "type": "long"
                  },
                  "type": {
                    "type": "keyword"
                  }
                }
              }
            }
          },
          "workflowId": {
            "type": "keyword"
          },
          "taskPath": {
            "type": "object",
            "enabled": false
          }
        }
      },
      "isError": {
        "type": "boolean"
      },
      "timestamp": {
        "type": "date"
      },
      "transactionId": {
        "type": "keyword"
      },
      "type": {
        "type": "keyword"
      }
    }
  }
}
