@esHost = http://elasticsearch.datastore.staging.tel.internal
@namespace = staging
@indexName = melonade-{{namespace}}-event


# @name createIndex
PUT {{esHost}}/{{indexName}}_new HTTP/1.1
Content-Type: application/json

{
  "mappings": {
    "event": {
      "dynamic": false,
      "properties": {
        "details": {
          "properties": {
            "ackTimeout": {
              "type": "date"
            },
            "createTime": {
              "type": "date"
            },
            "endTime": {
              "type": "date"
            },
            "input": {
              "type": "object",
              "enabled": false
            },
            "isRetried": {
              "type": "boolean"
            },
            "logs": {
              "type": "text"
            },
            "output": {
              "type": "object",
              "enabled": false
            },
            "parallelTasks": {
              "type": "object",
              "enabled": false
            },
            "dynamicTasks": {
              "type": "object",
              "enabled": false
            },
            "retries": {
              "type": "long"
            },
            "retryDelay": {
              "type": "long"
            },
            "startTime": {
              "type": "date"
            },
            "status": {
              "type": "keyword"
            },
            "tags": {
              "type": "keyword"
            },
            "taskId": {
              "type": "keyword"
            },
            "taskName": {
              "type": "keyword"
            },
            "taskReferenceName": {
              "type": "keyword"
            },
            "timeout": {
              "type": "long"
            },
            "transactionId": {
              "type": "keyword"
            },
            "type": {
              "type": "keyword"
            },
            "workflowDefinition": {
              "properties": {
                "description": {
                  "type": "text"
                },
                "failureStrategy": {
                  "type": "keyword"
                },
                "name": {
                  "type": "keyword"
                },
                "outputParameters": {
                  "type": "object",
                  "enabled": false
                },
                "rev": {
                  "type": "keyword"
                },
                "tasks": {
                  "type": "object",
                  "enabled": false
                }
              }
            },
            "workflowId": {
              "type": "keyword"
            },
            "taskPath": {
              "type": "object",
              "enabled": false
            },
            "parent": {
              "properties": {
                "transactionId": {
                  "type": "keyword"
                },
                "taskId": {
                  "type": "keyword"
                },
                "taskType": {
                  "type": "keyword"
                },
                "depth": {
                  "type": "long"
                }
              }
            },
            "transactionDepth": {
              "type": "long"
            },
            "decisions": {
              "type": "object",
              "enabled": false
            },
            "defaultDecision": {
              "type": "object",
              "enabled": false
            },
            "workflowRef": {
              "properties": {
                "name": {
                  "type": "keyword"
                },
                "ref": {
                  "type": "keyword"
                },
                "rev": {
                  "type": "keyword"
                }
              }
            }
          }
        },
        "isError": {
          "type": "boolean"
        },
        "timestamp": {
          "type": "date"
        },
        "transactionId": {
          "type": "keyword"
        },
        "type": {
          "type": "keyword"
        }
      }
    }
  },
  "settings": {
    "mapping": {
      "total_fields": {
        "limit": 2000
      }
    }
  }
}

###

# @name reindex
POST {{esHost}}/_reindex HTTP/1.1
Content-Type: application/json

{
  "source": {
    "index": "{{indexName}}"
  },
  "dest": {
    "index": "{{indexName}}_new"
  }
}

###

# @name addAliases
POST {{esHost}}/_aliases HTTP/1.1
Content-Type: application/json

{
  "actions": [
    {
      "add": {
        "alias": "{{indexName}}",
        "index": "{{indexName}}_new"
      }
    }
  ]
}

###

# @name delete
DELETE {{esHost}}/{{indexName}} HTTP/1.1
